# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoutubeApp
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'youtube-ios-player-helper'
  pod 'FloatingPanel'
  pod 'GoogleAPIClientForREST/YouTube'
  pod 'GoogleSignIn', '4.4.0'

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
#  pod 'IQKeyboardManagerSwift'
  
end
